name: Build My Lemuroid
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 17
      - uses: android-actions/setup-android@v3
      - name: Build APK
        run: ./gradlew assembleFreeDebug
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: my-lemuroid-apk
          path: '**/build/outputs/apk/**/*.apk'
